CREATE DATABASE Exercise1;
CREATE TABLE exercise1.EMP_1 (EMP_NUM CHAR(3) NOT NULL, EMP_Lname VARCHAR(15) NULL, EMP_Fname VARCHAR(15) NULL, EMP_INITIAL CHAR(1) NULL, 
	EMP_HIREDATE DATE NULL, JOB_CODE CHAR(3) NULL, PRIMARY KEY (EMP_NUM));
INSERT INTO exercise1.emp_1 (EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE) VALUES ('111', 'Red', 'Jeralph', 'O', '2001-09-18', '502');
INSERT INTO exercise1.emp_1 (EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE) VALUES ('112', 'Yumang', 'James Bernard', 'G', '2003-07-25', '502');
INSERT INTO exercise1.emp_1 (EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE) VALUES ('113', 'Banta', 'Jan Rusell', 'V', '2002-07-19', '502');
